### ISSUE TITLE
Local storage module?

### ISSUE THREAD

**Issue by isaacchansky** [AmpersandJS/tools.ampersandjs.com#11]
Didn't see anything on the tools.ampersandjs.com site but does something already exist for this? I'm thinking a mixin for using Localstorage or IndexedDB with ampersand-model/state/collection/etc...

**Comment by garrettn** [comment]
There is a [localStorage sync adapter](https://github.com/ConneXNL/ampersand-sync-localstorage), but it hasn't been published to npm yet.

I'm also working on an [adapter for localForage](https://github.com/garrettn/ampersand-sync-localforage), which uses the best available storage option (IndexedDB, Web SQL, localStorage). Unfortunately it's not quite ready for prime time.

**Comment by isaacchansky** [comment]
Thanks, guess I should have looked a little harder. LocalForage adapter looks nice, I'll keep an eye on that.

**Comment by HenrikJoreteg** [comment]
closing as this is not particularly actionable for the moment. I did add the idea as a trello card for the roadmap for voting, though: https://trello.com/c/zWhQ3n8y/39-some-sort-of-official-localstorage-mixin-for-collections
