### ISSUE TITLE
few suggestions

### ISSUE THREAD

**Issue by mattdesl** [AmpersandJS/tools.ampersandjs.com#12]
really enjoying the curated list so far. Couple more suggestions which are not related to ampersand, but have proven useful in my frontend workflow:
- [baboon-image-uri](https://www.npmjs.org/package/baboon-image-uri) ideal for unit testing images and quick prototypes, to avoid having to copy image files around
- [getusermedia](https://www.npmjs.org/package/getusermedia) abstraction
- [xhr](https://www.npmjs.org/package/xhr) abstraction
- [npm-dom](https://github.com/npm-dom/)

**Comment by HenrikJoreteg** [comment]
getusermedia was already there, added a few from npm-dom, thanks!
