### ISSUE TITLE
View that provides functionality for creating alerts/popups that close after a certain time.

### ISSUE THREAD

**Issue by ben-eb** [AmpersandJS/tools.ampersandjs.com#14]
Wrote this module last night, as I had a need to create a part of my application that is visible to the user only after a certain action - screen space is a premium! It's written in a generic, extendable way and leaves much of the hide/show implementation to the developer. It's also 100% covered using `tape` and `coverify`. :smiley:

I can PR this if you think it's a good addition to the list.

https://github.com/ben-eb/ampersand-auto-closing-view

Thanks!

**Comment by bear** [comment]
have you "announced" this to the AmpersandJS chat room?
