### ISSUE TITLE
Sound Effect Manager link is broken

### ISSUE THREAD

**Issue by mmacaula** [AmpersandJS/tools.ampersandjs.com#16]
Seems like the github link for sound-effect-manager is broken, github link points to https://github.com/henrikjoreteg/sound-effect-manager.js
instead of
https://github.com/HenrikJoreteg/SoundEffectManager

**Comment by wraithgar** [comment]
This is data that's pulled from the package.json in that project https://github.com/HenrikJoreteg/SoundEffectManager/blob/master/package.json

**Comment by kamilogorek** [comment]
Can we close this one as it has been already moved to @HenrikJoreteg repo?

**Comment by HenrikJoreteg** [comment]
fixed
