### ISSUE TITLE
ampersand-floatinglabel-input-view

### ISSUE THREAD

**Issue by mike-engel** [AmpersandJS/tools.ampersandjs.com#19]
Small input view extension to give developers the ability to use the [floating label pattern](http://bradfrost.com/blog/post/float-label-pattern/).

All tests passing (only ones pertaining to new functionality...didn't re-test inputView functionality :smile: )

https://github.com/datuhealth/ampersand-floatinglabel-input-view

**Comment by HenrikJoreteg** [comment]
added, thanks! sorry for the delay.
