### ISSUE TITLE
Concert.js

### ISSUE THREAD

**Issue by moll** [AmpersandJS/tools.ampersandjs.com#26]
Hey,

For those who like `Backbone.Events`, I created [Concert.js](https://github.com/moll/js-concert) a few years ago as an alternative. Just updated it to support binding extra arguments in addition to the context. ;-)

Cheers

**Comment by HenrikJoreteg** [comment]
added, thanks! sorry for the delay.

**Comment by moll** [comment]
No biggie. Thanks!

PS. Is it me or does http://tools.ampersandjs.com/ load to an empty page?

**Comment by HenrikJoreteg** [comment]
um.... not sure what's happening here, the JS file built properly and exists when i hit it directly in the browser, but it's 404'ing as a resource for the page. Super odd, i pinged @bear to check for DNS issues.

**Comment by HenrikJoreteg** [comment]
I added a '/' as the resource prefix and it seems to have resolved it... quite odd. Anyway, thanks!

**Comment by moll** [comment]
What are you seeing when you look at the source of that?
I see a page missing `<html>` et al.

``` html
<!DOCTYPE html>
<link href="resources.bf4f90e9.min.css" rel="stylesheet" type="text/css">
<script src="resources.60633f66.min.js"></script>
```
