### ISSUE TITLE
New module: Isomorphic sanitized HTML data type for Ampersand.js

### ISSUE THREAD

**Issue by mikepb** [AmpersandJS/tools.ampersandjs.com#27]
# Sanitized HTML data type for Ampersand

This module implements an isomorphic sanitized HTML data type for Ampersand.js. On the server, Google's Gumbo HTML parser is used to parse and sanitize the HTML data. In the browser, the sanitized value is used when rendering user-generated content.
## More information
- [GitHub](https://github.com/mikepb/ampersand-sanitized-html-data-type)
- [NPM](https://www.npmjs.com/package/ampersand-sanitized-html-data-type)

**Comment by HenrikJoreteg** [comment]
added, thanks! sorry for the delay.
