### ISSUE TITLE
Fluxible Store mixins for Ampersand State, Model, and Collection

### ISSUE THREAD

**Issue by mikepb** [AmpersandJS/tools.ampersandjs.com#28]
**Ampersand Collection Fluxible Mixin**

This module implements the dehydrate and rehydrate methods for Ampersand.js states and models to be used as Fluxible Stores.

https://github.com/mikepb/ampersand-state-fluxible-mixin

**Ampersand Collection Fluxible Mixin**

This module implements the dehydrate and rehydrate methods for Ampersand.js collections to be used as Fluxible Stores.

https://github.com/mikepb/ampersand-collection-fluxible-mixin

**Comment by HenrikJoreteg** [comment]
added, thanks! sorry for the delay.
