### ISSUE TITLE
`npm build` errors

### ISSUE THREAD

**Issue by lukekarrys** [AmpersandJS/tools.ampersandjs.com#3]
Errors on `Error: Cannot find module 'backbone'` and then if I install that `Error: Cannot find module 'human-view'`.

I can install both of those easily from npm but then trying to get the site running locally it errors with (with `developmentMode: false`)

`Uncaught TypeError: Property '$' of object #<Object> is not a function`

![screen shot 2014-03-31 at 3 28 36 pm](https://cloud.githubusercontent.com/assets/542108/2573673/ddec33b8-b923-11e3-8809-9a4c25d1c4c8.png)

Are there other deps missing?

**Comment by HenrikJoreteg** [comment]
i started converting this to all ampersand modules and it worked after i removed backbone, etc from dependencies, turned out it worked because they were still in my node_modules. Finished cleaning that up now, no more backbone.
