### ISSUE TITLE
Ampersand Multi-Select View

### ISSUE THREAD

**Issue by kylefarris** [AmpersandJS/tools.ampersandjs.com#32]
I needed the ability to have multi-select selectboxes so I created this. Based on the regular ampersand-select-view.

https://www.npmjs.com/package/ampersand-multiselect-view

EDIT: I made this after I realized it was more-or-less impossible to simply extend the `ampersand-select-view` by supplying a modified template with the 'multiple' parameter. There are fundamental assumptions (like default selection) within the `ampersand-select-view` that will not allow a multiselect-style select box to work in an expected manner.

**Comment by HenrikJoreteg** [comment]
added: http://tools.ampersandjs.com/?q=multiselect
