### ISSUE TITLE
404 for resources.js

### ISSUE THREAD

**Issue by dhritzkiv** [AmpersandJS/tools.ampersandjs.com#34]
It seems that tools.ampersandjs.com isn't loading. The culprit may be a missing `resources.{guid}.min.js`

**Comment by HenrikJoreteg** [comment]
ugh... sorry, just now saw this. At some point we switched off of using github pages for this, I just requested we switch it back. Either way we'll get it resolved. I asked @nlf from &yet ops to take a look.

**Comment by nlf** [comment]
this should be fixed now, though give it a few minutes for dns to propagate. reopen the issue if it's still broken tomorrow and i'll look again :)
