### ISSUE TITLE
ampersand-links for catching all anchors in a document

### ISSUE THREAD

**Issue by alexserver** [AmpersandJS/tools.ampersandjs.com#36]
I took a course of @HenrikJoreteg  where he specifies that in order to do a real SPA, we should capture all anchors in a React component and call `event.preventDefault()` to stop the browser do a traditional http request, and call ampersand-router history navigate function. Here is the code of the course:

https://github.com/HenrikJoreteg/masters/blob/master/src/components/nav-helper.js#L8-L15

```
  onClick (event) {
    const pathname = localLinks.getLocalPathname(event)

    if (pathname) {
      event.preventDefault()
      app.router.history.navigate(pathname)
    }
  },
```

I was thinking, since this is a fundamental task of any SPA, shouldn't this be automated within an ampersand module ? I'm thinking of having an `ampersand-links` that navigates all anchors withing DOM, or listen to click event, and does this, in order to not write these 6 lines of code in every project.

What do you think ?

**Comment by HenrikJoreteg** [comment]
Hi @alexserver. I would tend to agree. The only problem is that it's not entirely clear exactly what you're going to want to do when that event happens. You can't assume `app.router.history.navigate(pathname)` is where it lives for example.

But yeah, also... there's this: https://github.com/HenrikJoreteg/react-internal-nav which lets you simply supply an `onInternalNav` callback.

**Comment by alexserver** [comment]
thanks @HenrikJoreteg .
So for now this is the best approach.

**Comment by HenrikJoreteg** [comment]
Yeah, Its quite simple to just hook up this component once and be done.
