### ISSUE TITLE
Add visible-element

### ISSUE THREAD

**Issue by joeybaker** [AmpersandJS/tools.ampersandjs.com#4]
https://github.com/joeybaker/visible-element

A module of mine that might be a good addition?

**Comment by HenrikJoreteg** [comment]
Conceptually, yes. But I feel like assuming that `$` exists and works a certain way is something we'd like to avoid. I also realize there's no way you would have known that so we need to document the criteria for inclusion. 

Hence I opened this ticket: https://github.com/AmpersandJS/tools.ampersandjs.com/issues/5

**Comment by joeybaker** [comment]
Totally fair. Thanks.
