### ISSUE TITLE
location-bar

### ISSUE THREAD

**Issue by KidkArolis** [AmpersandJS/tools.ampersandjs.com#6]
I didn't find any routing related modules on tools.ampersandjs.com yet.

location-bar is a small (tiny?) module which just updates the location bar (or url bar) of the browser and listens to it's changes. It supports pushState and hash change.

Actually, it's just code copy pasted from Backbone, but it's just the Backbone.History bit and nothing else.

https://www.npmjs.org/package/location-bar

**Comment by wraithgar** [comment]
Looks like it just didn't make it onto the site? https://github.com/AmpersandJS/ampersand-router

**Comment by latentflip** [comment]
Interesting. I've added ampersand-router to tools list. Ampersand-router has ampersand-history within it (which itself is basically just Backbone.History).

@KidkArolis is location-bar useful on it's own? If so we could add it as well (and perhaps even just depend on it from ampersand-router?)

**Comment by KidkArolis** [comment]
I personally found it useful when building a router (https://github.com/QubitProducts/cherrytree). I needed a library that could update URL bar and listen to it's changes, but I didn't need any of backbone's url pattern maching logic which is found in Backbone.Router. Backbone.History is a really nice and robust abstraction of the pushState / hash change APIs so it was a perfect choice.

A standalone Backbone.History is not the most "in demand" library out there, but in the spirit of not having to solve the same problem twice it would be nice to split the Router and History into 2 so everyone could use whichever they need.

One example of where a standalone Backbone.History lib (aka location-bar) would be useful is for someone using https://github.com/tildeio/router.js router. Router.js has all of the routing logic, but it doesn't deal with updating url/pushState/hash change. (router.js differs from Backbone.Router in that it supports nested routes where each route gets to load some data, etc. and handles async transitions nicely.)

One reason I can see it being bad to split ampersand-router into 2 things is that it could potentially confuse people - which one do I use for my routing? - they both do pushStaty stuff, etc. But if one is named 'router' and the other one is described as a lower level pushState/hash change abstraction then perhaps the distinction would be clear enough.

Anyways, hope this is useful.

**Comment by latentflip** [comment]
@KidkArolis thanks! cherrytree looks interesting too. Personally I've been thinking about how to make routing better, so I'll definitely check that out.

Gonna chat with @HenrikJoreteg but it sounds like it might make sense to have a standalone thing like location-bar in here :)

**Comment by HenrikJoreteg** [comment]
Thanks for you suggestion @KidkArolis. Since this is mainly a collection of modules for ampersand users, I'm going to close this for now. That's not to say that I don't like having a cleanly split out history/location-bar module. But if there's something we can improve there i think it'd be better to do that via a PR for changes to ampersand-router. Thanks again (sorry this was sitting there so long).

**Comment by jamesplease** [comment]
> Personally I've been thinking about how to make routing better, so I'll definitely check that out.

@latentflip, I know it's been a year, but if you're still interested in this then you should ping me sometime! I'm (lazily) working on [Backbone v2's router/history](https://github.com/jashkenas/backbone/pull/3660), while also doing [some very thorough research](https://github.com/jmeas/router-comparison) into client side routers. I'm also designing a new standalone router that will likely form the foundation of Marionette's new router.

Anyway, I guess it needn't be said but I am super interested in client side routing, and I would love to chat about it with ya!
